<?php
/**
 * Created by PhpStorm.
 * User: Luka
 * Date: 01/03/15
 * Time: 10:20
 */
?>
<div id="scroll">
<table id="narudzbe" border="1">
    <tr>
        <th>Sifra</th>
        <th>Ime kupca</th>
        <th>Adresa dostave</th>
        <th>Ukupna cijena</th>
        <th>Datum</th>
    </tr>
    <?php foreach($pageN->items as $narudzba) { ?>
    <tr>
        <td><?php echo $narudzba->sifra_N?></td>
        <td><?php echo $narudzba->ime_kupca?></td>
        <td><?php echo $narudzba->adresa_dostava?></td>
        <td><?php echo $narudzba->ukupna_cijena?></td>
        <td><?php echo $narudzba->datum?></td>
    </tr>
    <?php } ?>
</table>
</div>

<div>
    <?php
    echo Phalcon\Tag::form("pregled/index");
    echo Phalcon\Tag::textField(array(
        "name" => "sifra",
        "id" => "odabir",
        "size" => 10
    ));
    echo Phalcon\Tag::submitButton(array(
        "value" => "dada",
        "name" => "prikazi",
        "id" => "prikazStavki"
    ))
    ?>
    </form>
</div>

<div>
<table>
    <tr>
        <th>Sifra stavke</th>
        <th>Sifra artikla</th>
        <th>Naziv artikla</th>
        <th>Cijena</th>
    </tr>
    <?php foreach ($pageS->items as $stavka) { ?>
    <tr>
        <td><?php echo $stavka->sifra_S ?> </td>
        <td><?php echo $stavka->sifra_A ?> </td>
        <td><?php echo $stavka->naziv_A ?> </td>
        <td><?php echo $stavka->ukupna_cijena ?> </td>
    </tr>
    <?php } ?>
</table>
</div>
