<?php
/**
 * Created by PhpStorm.
 * User: Luka
 * Date: 27/02/15
 * Time: 11:47
 */
use Phalcon\Tag;
use Phalcon\Forms\Element\Select;
?>

<form>
    <?php
    echo Phalcon\Tag::select(array(
        "Artikal",
        Artikal::find(),
        "using" => array("naziv", "naziv"),
        "size" => 4
    ));
    ?>
</form>
<br>

<button type="button" onclick="puniKosaricu()">Dodaj artikl</button>

<?php echo Phalcon\Tag::form("narudzba/stvori"); ?>

<select id="kosarica" name="kosarica[]" size="8" multiple>
</select>
<button type="button" onclick="removeArtikl()">Makni Artikl</button>
<br>
<br>
<input id="ImeKupca" type="text" /><label>Vaše ime</label>
<input id="AdresaKupca" type="text" /><label>Adresa na koju želite dostavu</label>
<br>
<button type="submit" onclick="selectAll()">Spremi narudžbu</button>

</form>


