
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("store/new", "Create store")) ?>
</div>

<?php echo $this->tag->form(array("store/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search store</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="store_id">Store</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("store_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="location">Location</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("location", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="size">Size</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("size", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="address">Address</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("address", "size" => 30)) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
