
<?php echo $this->tag->form("store/create") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("store", "Go Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

<?php echo $this->getContent(); ?>

<div align="center">
    <h1>Create store</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="location">Location</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("location", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="size">Size</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("size", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="address">Address</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("address", "size" => 30)) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

</form>
